[lintspec]
paths = []
exclude = [
    './contracts/mock',
    './contracts/solutions/Carbon/common/UsdtOFT.sol',
    './contracts/solutions/Carbon/common/interfaces/IUsdtOFT.sol',
    './contracts/solutions/mrETH/external',
    './contracts/common/mUSDLock.sol',
    './contracts/core/MoleculaPoolTreasury.sol',
    './contracts/core/SupplyManager.sol',
    './contracts/core/MoleculaPoolTreasuryV2.sol',
    './contracts/executor/interfaces/ILayerZeroReceiveUlnView.sol',
    './contracts/executor/interfaces/ILayerZeroReceiveUlnView.sol',
    './contracts/common/rebase/structures/OperationStatus.sol',
    './contracts/test',
    './lib',
    './test/',
]
inheritdoc = false
notice_or_dev = false
skip_version_detection = true

[output]
json = false
compact = true
sort = false

[constructor]
notice = "ignored"
dev = "required"
param = "required"

[enum]
notice = "ignored"
dev = "required"
param = "required"

[error]
notice = "ignored"
dev = "required"
param = "required"

[event]
notice = "ignored"
dev = "required"
param = "required"

[function.private]
notice = "ignored"
dev = "required"
param = "required"
return = "required"

[function.internal]
notice = "ignored"
dev = "required"
param = "required"
return = "required"

[function.public]
notice = "ignored"
dev = "required"
param = "required"
return = "required"

[function.external]
notice = "ignored"
dev = "required"
param = "required"
return = "required"

[modifier]
notice = "ignored"
dev = "required"
param = "required"

[struct]
notice = "ignored"
dev = "required"
param = "required"

[variable.private]
notice = "ignored"
dev = "required"

[variable.internal]
notice = "ignored"
dev = "required"

[variable.public]
notice = "ignored"
dev = "required"
return = "ignored"
