[profile.default]
src = 'contracts'
out = 'build'
libs = ['lib', 'node_modules']
test = 'test'
cache_path  = 'cache_forge'
build_info = true
build_info_path = 'build/build-info'
auto_detect_remappings = false
optimizer = true
optimizer_runs = 400

fs_permissions = [
  { access = "read-write", path = ".forge-snapshots/" },
  { access = "read", path = "build/" }
]

remappings = [
    "@chainlink/=../../node_modules/@chainlink/",
    "@openzeppelin/=node_modules/@openzeppelin/", 
    "@layerzerolabs/=node_modules/@layerzerolabs/",
    "@aave/=node_modules/@aave/",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/"
]

compilation_restrictions = [
    { paths="contracts/solutions/Carbon/", version = "=0.8.24" },
    { paths="contracts/test/UsdtTron.sol", version = "=0.4.20" },
    { paths="contracts/test/UsdtEthereum.sol", version = "=0.4.18" },
]

[doc]
ignore = ["contracts/test/**/*.sol", "contracts/mock/**/*.sol"]

[profile.default.fuzz]
runs = 1024
show_metrics = true

[rpc_endpoints]
mainnet = "${JSON_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHEREUM_API_KEY}" }
mainnet = { key = "${ETHEREUM_API_KEY}" }