// Export typechain;

export * from '../typechain';

export * from '../typechain/common';

export type {
    AccountantAgent,
    AgentLZ,
    CommonTokenVault,
    Executor,
    ICurveStableSwapFactoryNG,
    ICurveStableSwapNG,
    IAgent,
    IERC20Basic,
    IERC20Metadata,
    ILayerZeroEndpointV2,
    IMoleculaPoolV2,
    IOracle,
    MoleculaPoolTreasury,
    MoleculaPoolTreasuryV2,
    MUSDE,
    MUSDLock,
    NativeTokenVault,
    NitrogenTokenVault,
    RebaseToken,
    RebaseTokenV2,
    ShareToken,
    SupplyManager,
    SupplyManagerV2,
    TokenVault,
    UsdtOFT,
} from '@molecula-monorepo/solidity/typechain-types';

const contractsNames = [
    'AavePool',
    'AccountantAgent',
    'AgentLZ',
    'Aragon',
    'CommonTokenVault',
    'EndpointLZ',
    'ERC20',
    'ERC4626',
    'ExecutorLZ',
    'ICurveStableSwapFactoryNG',
    'ICurveStableSwapNG',
    'IAgent',
    'IERC20Basic',
    'IERC20Metadata',
    'IMoleculaPoolV2',
    'IOracle',
    'MoleculaPoolTreasury',
    'MoleculaPoolTreasuryV2',
    'MUSDE',
    'MUSDLock',
    'NativeTokenVault',
    'NitrogenTokenVault',
    'RebaseToken',
    'RebaseTokenV2',
    'ReceiveULN',
    'SavingsUSDS',
    'SendULN',
    'SFrxUSD',
    'ShareToken',
    'SparkPool',
    'StakedUSDe',
    'SupplyManager',
    'SupplyManagerV2',
    'SwapCurve',
    'TokenVault',
    'UsdtOFT',
] as const;

export type ContractNameType = (typeof contractsNames)[number];
